name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: test
        run: |
          export SECRET_TOKEN='p&l%385148kslhtyn^##a1)ilz@4zqj=rq&agdol^##zgl9(vs'
          export HOSTS='*'
          pip install --upgrade pip
          pip install -r requirements.txt
          pytest
